# Generated by Django 5.0 on 2024-04-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
